### ISSUE TITLE
File sizes without gzip?

### ISSUE THREAD

**Issue by mgrsskls** [GoogleChromeLabs/psi#35]
Hi,

I just realised that the reported file sizes of gzipped documents seem to be the ones without gzip.
E.g., the html file of www.mgrossklaus.de is about 16kb without gzip, 6kb with gzip (which is activated) and psi reports a file size of 16kb. Same for css and html5rocks.com, e.g.

Indeed I have no idea if it's actually a bug / fixable since you request the files via command line.

Thanks a lot!

![bildschirmfoto 2014-09-16 um 18 49 59](https://cloud.githubusercontent.com/assets/1113765/4291121/bad8c45e-3dc1-11e4-95a8-58f6801c2991.png)
![bildschirmfoto 2014-09-16 um 18 51 53](https://cloud.githubusercontent.com/assets/1113765/4291143/ee9ae772-3dc1-11e4-950e-7a77ad735749.png)

**Comment by sindresorhus** [comment]
Not much we can do about it then.

@addyosmani Can you open an internal ticket about getting the gzipped sizes too?

**Comment by addyosmani** [comment]
Can do. Thanks for the reminder.

**Comment by nickcolley** [comment]
Could we detect if GZIP is enabled and calculate it ourselves?
