### ISSUE TITLE
How to get localized formattedOutput?

### ISSUE THREAD

**Issue by jmartsch** [GoogleChromeLabs/psi#54]
When I use the following code with locale: 'de_DE' I don´t get localized messages, just the english ones. How can I fix this?

``` javascript
var sites = ['http://www.html5rocks.com'];
gulp.task('mobile', function () {
    sites.forEach(function (site) {
        return psi.output(site, {
            // key: key
            nokey: 'true',
            strategy: 'mobile',
            locale: 'de_DE'
        }, function (err) {
            console.log(err);
        });
    })

});
```

**Comment by DanielRuf** [comment]
I guess you mean https://github.com/addyosmani/psi/blob/master/lib/utils.js

These are not translated.
But this definitely works: 
```js
psi.output(url, {strategy: 'desktop',locale:'de_DE'}).then(data => {
  console.log(data.formattedResults)
});
```

**Comment by sindresorhus** [comment]
We should probably document that fact in the `psi.output` docs. And also maybe remove the `--locale` flag. It would have the same problem, which makes it useless, at least from what I can tell.

**Comment by exterkamp** [comment]
This works now for lab data :smile: :de: 
![image](https://user-images.githubusercontent.com/6392995/65277532-f33d8180-dade-11e9-987a-0b85adcf2e4c.png)

Translating Field data and the titles are a future enhancement to think about.
