### ISSUE TITLE
Adding fonts as a separate response type

### ISSUE THREAD

**Issue by ahallicks** [GoogleChromeLabs/psi#69]
I'm using this awesome tool as part of a project perf tester and it's great! The only thing is I can't see where fonts are included. Do they come under otherResponseBytes?

I notice that in the Page Speed docs they have a separate response for flash resources(!?) but not fonts. I think this would be a useful thing to measure with some of the heavy font-loading sites I've seen recently.

I'm not sure if this is something for this tool or PageSPeed Insights itself so apologies if this is the wrong place to ask.

**Comment by DanielRuf** [comment]
I guess this has to be implemented on the API side as psi only formats the results from the API.

**Comment by DanielRuf** [comment]
https://github.com/googleapis/googleapis

**Comment by exterkamp** [comment]
This seems like v1-v4 question. Reopen if this is still relevant to v5+!
