### ISSUE TITLE
psi doesn't return usability score for desktop strategy

### ISSUE THREAD

**Issue by alphara** [GoogleChromeLabs/psi#72]
psi(url, {strategy: 'mobile'}) return both speed and usability scores: 
ruleGroups: { SPEED: { score: 58 }, USABILITY: { score: 93 } }

But 
psi(url, {strategy: 'desktop'}) return just speed score:
ruleGroups: { SPEED: { score: 74 } }

It doesn't return usability score for desktop strategy.

**Comment by DanielRuf** [comment]
Well, this should be filed as issue at https://github.com/google/google-api-nodejs-client

https://www.googleapis.com/pagespeedonline/v2/runPagespeed?url=https://github.com

**Comment by JustinBeckwith** [comment]
👋 greetings folks!  This one is weird.  At the end of the day, the nodejs api client is really just calling the underlying apiary APIs.  From the API explorer, it seems like I *only* ever get back a speed score.  I am using this to test the underlying API:

https://developers.google.com/speed/docs/insights/v4/reference/pagespeedapi/runpagespeed

I'm setting the following parameters:
- url: https://github.com
- strategy: mobile

When I run this query, I get results like this:
https://gist.github.com/JustinBeckwith/06bc533e786570e35892a6fd7e4f2ea9

This has only a single ruleGroup returned, and it's "SPEED".  Am I properly understanding how y'all are trying to use the API?

**Comment by DanielRuf** [comment]
It uses the old API. There is a newer one.

**Comment by JustinBeckwith** [comment]
Ah, just so I remember what this means later - the ref docs are using v4 of the API, and PSI is using v2 of the API.

**Comment by DanielRuf** [comment]
See https://github.com/addyosmani/psi/issues/78

**Comment by JustinBeckwith** [comment]
*scratches head* still having issues with this one.  I put together a test that uses `googleapis` to get the score, and directly hitting the API using `axios`.  Here's the code:

```js
const {google} = require('googleapis');
const axios = require('axios');

async function runPSO() {
  console.log('Running googleapis test....')
  const psi = google.pagespeedonline('v2');
  const res = await psi.pagespeedapi.runpagespeed({
    url: 'https://github.com',
    strategy: 'desktop'
  });
  console.log(res.data);
}

async function runRaw() {
  console.log('Running REST test...');
  const res = await axios.get(
    'https://www.googleapis.com/pagespeedonline/v2/runPagespeed',
    {
      params: {
        url: 'https://github.com',
        strategy: 'desktop'
      }
    }
  );
  console.log(res.data);
}

async function main() {
  await runPSO();
  await runRaw();
}

main().catch(console.error);
```

The results are:

```
Running googleapis test....
{ captchaResult: 'CAPTCHA_NOT_NEEDED',
  kind: 'pagespeedonline#result',
  id: 'https://github.com/',
  responseCode: 200,
  title: 'The world\'s leading software development platform · GitHub',
  ruleGroups: { SPEED: { score: 45 } },
  pageStats: 
   { numberResources: 48,
     numberHosts: 7,
     totalRequestBytes: '5910',
     numberStaticResources: 42,
     htmlResponseBytes: '55802',
     cssResponseBytes: '563445',
     imageResponseBytes: '1700091',
     javascriptResponseBytes: '754073',
     otherResponseBytes: '2010',
     numberJsResources: 4,
     numberCssResources: 3 },
  formattedResults: 
   { locale: 'en_US',
     ruleResults: 
      { AvoidLandingPageRedirects: [Object],
        EnableGzipCompression: [Object],
        LeverageBrowserCaching: [Object],
        MainResourceServerResponseTime: [Object],
        MinifyCss: [Object],
        MinifyHTML: [Object],
        MinifyJavaScript: [Object],
        MinimizeRenderBlockingResources: [Object],
        OptimizeImages: [Object],
        PrioritizeVisibleContent: [Object] } },
  version: { major: 1, minor: 15 } }
Running REST test...
{ captchaResult: 'CAPTCHA_NOT_NEEDED',
  kind: 'pagespeedonline#result',
  id: 'https://github.com/',
  responseCode: 200,
  title: 'The world\'s leading software development platform · GitHub',
  ruleGroups: { SPEED: { score: 45 } },
  pageStats: 
   { numberResources: 48,
     numberHosts: 7,
     totalRequestBytes: '5910',
     numberStaticResources: 42,
     htmlResponseBytes: '55802',
     cssResponseBytes: '563444',
     imageResponseBytes: '1700080',
     javascriptResponseBytes: '754069',
     otherResponseBytes: '2010',
     numberJsResources: 4,
     numberCssResources: 3 },
  formattedResults: 
   { locale: 'en_US',
     ruleResults: 
      { AvoidLandingPageRedirects: [Object],
        EnableGzipCompression: [Object],
        LeverageBrowserCaching: [Object],
        MainResourceServerResponseTime: [Object],
        MinifyCss: [Object],
        MinifyHTML: [Object],
        MinifyJavaScript: [Object],
        MinimizeRenderBlockingResources: [Object],
        OptimizeImages: [Object],
        PrioritizeVisibleContent: [Object] } },
  version: { major: 1, minor: 15 } }
```

As far as I can tell - we are returning the exact same data using the npm module as you would get talking to the API directly.  It's entirely possible the backend service implementation changed :/  I'm going to close out the issue in the other repository.  If you can reproduce an issue where the API behaves differently than the results returned from the npm module... let me know!
