### ISSUE TITLE
How to return the data received from PageSpeed Insight from node in a route?

### ISSUE THREAD

**Issue by bluerid** [GoogleChromeLabs/psi#73]
I am using the PSI npm package in a simple route. Used the psi method from the library. However, the script does not wait for the expected result. It works Ok in console. However, I need to return the response to browser and display it there. How can I do this? 
Note: psi method a Promise.

```
app.get('/psi', function(req, res){
    res.type('text/html');
    return psi('example.com',{ key: '*Iz*Sy*****PiZ***wz7****sy*****', strategy: 'desktop'}).then( data => {
        console.log('Speed score: ' + data.ruleGroup.SPEED.score);
        console.log('done');
        res.json({ 'results' : data.ruleGroup.SPEED.score });
    });

});
```

**Comment by DanielRuf** [comment]
You need a promise based approach or  callback.
