### ISSUE TITLE
Google APIs screenshot

### ISSUE THREAD

**Issue by hazemhagrass** [GoogleChromeLabs/psi#80]
Hi,
Google APIs is supporting retrieving a screenshot from the result.
Is this supported on your plugin?
<img width="1082" alt="screen shot 2017-08-28 at 2 36 47 pm" src="https://user-images.githubusercontent.com/3625423/29773575-5e56512c-8bfe-11e7-87ed-764c13a7cfc6.png">

**Comment by DanielRuf** [comment]
Obviously so far not, so this would need to be implemented.

**Comment by DanielRuf** [comment]
See https://github.com/google/google-api-nodejs-client/blob/master/src/apis/pagespeedonline/v2.ts#L51

**Comment by exterkamp** [comment]
In v5+ the API returns `final_screenshot` and filmstrips as data uris.  Not sure how we'd expose them on cli, maybe saving them as images and then linking to them with a flag. 

If that's interesting post it here as a possible enhancement.

**Comment by JuanMaRuiz** [comment]
Hi @exterkamp maybe it's not necessary to expose on cli but we could save them, as you say.

I think filmstrips could be useful for users than want to make performance regression tests. What do you think? 

Best regards.

**Comment by paulirish** [comment]
if anyone is making regression tests then they should just work with the JSON data directly. i dont think this utility saving the datauris to disk would be too helpful.

**Comment by JuanMaRuiz** [comment]
> if anyone is making regression tests then they should just work with the JSON data directly. i dont think this utility saving the datauris to disk would be too helpful.

You are right, this utility should only provide the data. Users should be on charge of saving (or not) the data if they need to.

**Comment by DanielRuf** [comment]
Exactly. So is there still something needed / missing that users can get / consume this data?

**Comment by JuanMaRuiz** [comment]
The data the user can consume as json is the same as psi shows by default. So if filmstrips (or whatever) has value for the user it should be added.

**Comment by JuanMaRuiz** [comment]
> Exactly. So is there still something needed / missing that users can get / consume this data?

As @exterkamp said filmstrips are returned by v5 but psi tool is not exposing that data. Maybe it could be added to the json output (under a flag) so the user could use that.

**Comment by exterkamp** [comment]
+1 to @paulirish & @JuanMaRuiz, this data is accessible to the user already.

I think this could be part of a cookbook on how to do common things, like getting screenshots out of a result e.g. the code that @JuanMaRuiz made. Maybe a doc opportunity?

**Comment by JuanMaRuiz** [comment]
@exterkamp I think it would be a good idea to document it. Where should be the cookbook/doc placed? Maybe as a wiki page within this repo? Maybe gulp/grunt/ ... examples could be added there as well. What do you think? Make it sense for you?

**Comment by exterkamp** [comment]
Didn't see that there was a question directed at me here, whoops!

Could add it to the main readme in a cookbook section? Maybe put it in a `<details>` element similar to [these](https://github.com/treosh/lighthouse-ci-action#recipes)? Maybe "Getting PSI into your build process" also belongs in a details element in a "Common Use cases" section.

**Comment by JuanMaRuiz** [comment]
> Didn't see that there was a question directed at me here, whoops!
> 
> Could add it to the main readme in a cookbook section? Maybe put it in a `<details>` element similar to [these](https://github.com/treosh/lighthouse-ci-action#recipes)? Maybe "Getting PSI into your build process" also belongs in a details element in a "Common Use cases" section.

SGTM the idea of a **Recipes** section. I can try and make a PR with the proposal. Does that sound good to you @exterkamp ?

Best regards.

**Comment by exterkamp** [comment]
Sounds like a plan!

**Comment by JuanMaRuiz** [comment]
Hi @exterkamp PR was merged. I think this issue cloud be closed, isn't it?

**Comment by exterkamp** [comment]
Yup!
