### ISSUE TITLE
gulp PSI stuck and not working

### ISSUE THREAD

**Issue by balasivagnanam** [GoogleChromeLabs/psi#81]
I tried to use gulp to automate this step, But for some reason it is stuck with psi-desktop task and not moving forward. Below is the result

> C:\Codes\dxd-codemig-test>gulp psi
> [18:24:35] Using gulpfile C:\Codes\dxd-codemig-test\gulpfile.js
> [18:24:35] Starting 'psi-seq'...
> [18:24:35] Starting 'browser-sync-psi'...
> [18:24:35] Finished 'browser-sync-psi' after 50 ms
> [18:24:35] Starting 'ngrok-url'...
> [Browsersync] Access URLs:
>  --------------------------------------
>        Local: http://localhost:3020
>     External: http://169.254.87.88:3020
>  --------------------------------------
>           UI: http://localhost:3001
>  UI External: http://169.254.87.88:3001
>  --------------------------------------
> [Browsersync] Serving files from: app
> serving your tunnel from: https://ec3992f5.ngrok.io
> [18:24:38] Finished 'ngrok-url' after 2.3 s
> [18:24:38] Starting 'psi-desktop'...
> 
> --------------------------------------------------------
> 
> URL:       ec3992f5.ngrok.io
> Strategy:  desktop
> Speed:     98
> 
> Hosts                                      | 1
> Resources                                  | 1
> Other size                                 | 1.71 kB
> Total size of request bytes sent           | 39 B
> 
> Main resource server response time         | 1.35
> 
> --------------------------------------------------------

My gulpfile.js
```
// this is where your server task goes. I'm using browser sync
gulp.task('browser-sync-psi', function() {
    browserSync({
        port: portVal,
        open: false,
        server: {
            baseDir: 'app'
        }
    });
});

// psi sequence with 'browser-sync-psi' instead
gulp.task('psi-seq', function(cb) {
    return sequence(
        'browser-sync-psi',
        'ngrok-url',
        'psi-desktop',
        'psi-mobile',
        cb
    );
});

// psi task runs and exits
gulp.task('psi', ['psi-seq'], function() {
    console.log('Woohoo! Check out your page speed scores!')
    process.exit();
})

gulp.task('ngrok-url', function(cb) {
    return ngrok.connect(3000, function(err, url) {
        site = url;
        console.log('serving your tunnel from: ' + site);
        cb();
    });
});

gulp.task('psi-desktop', function(cb) {
    psi.output(site, {
        nokey: 'true',
        strategy: 'desktop'
    }, cb);
});

gulp.task('psi-mobile', function(cb) {
    psi.output(site, {
        nokey: 'true',
        strategy: 'mobile'
    }, cb);
});
```

**Comment by DanielRuf** [comment]
You might want to check the exit codes of the psi tasks and if there are errors thrown.

**Comment by DanielRuf** [comment]
Did you use https://github.com/addyosmani/psi-gulp-sample as template?

**Comment by exterkamp** [comment]
Closing from inactivity.
