### ISSUE TITLE
npm still installs V2

### ISSUE THREAD

**Issue by adamjermstad** [GoogleChromeLabs/psi#99]
#97 #98 
I'm assuming because the package version has been at 3.1.0 since 2c24a60 (Jan 22, 2018), npm is still installing code using the V2 PageSpeed Insights API. Given that the package has been updated to use V4 and now V5 of the API, can the version of this package be updated and published to npm?

**Comment by exterkamp** [comment]
Hm, yup need to make a new release.  Good call.

**Comment by jjmoorhouse** [comment]
would be pretty handy if you could push the latest version to npm....

**Comment by exterkamp** [comment]
Haha, yup, I just need to pester the right people to get access to do it or have them do it @addyosmani / @paulirish!

**Comment by addyosmani** [comment]
@exterkamp you should be all set now! https://www.npmjs.com/package/psi

**Comment by ftanrisevdi** [comment]
I wonder when we can use the 4.0.0 version, [npm](https://www.npmjs.com/package/psi) is still 3.1.0?

**Comment by exterkamp** [comment]
This is purely because I am behind :sob: 

We'll land #104 then release a 4.0.1 to npm.

**Comment by exterkamp** [comment]
Updated! Sorry this took so long!
